image: alpine/make:latest
pages:
  script:
    - mkdir .public
    - make base-gitlabio
    - make clean
    - make all
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
